Make layout and font-size responsive
windresistance/andC pull request #3
Opened 2021-01-23 13:35 UTC by antoine-boue

2021-01-23 15:22 UTC, windresistance requested changes

2021-01-23 15:22 UTC, windresistance commented on assets/styles/sass/styles.scss
> +@import "shared/reset";
shouldn't the reset come first?

2021-01-23 16:24 UTC, antoine-boue commented on assets/styles/sass/styles.scss
> +@import "shared/reset";
But we use the mixins in the reset file.

2021-01-24 02:33 UTC, windresistance commented on assets/styles/sass/styles.scss
> +@import "shared/reset";
Roger that. Reset should always come first, but yeah in this case I guess we can't. Makes me think we should just combine shared and reset into one file. What do you think?

2021-01-24 02:34 UTC, windresistance approved these changes

2021-01-24 04:37 UTC, antoine-boue commented on assets/styles/sass/styles.scss
> +@import "shared/reset";
Agreed

2021-01-24 08:39 UTC, merged